# Generated by Django 5.1.6 on 2025-03-01 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='files',
            field=models.FileField(default='uploads/default.pdf', upload_to='uploads/'),
        ),
    ]
